services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: shop-sphere-jenkins_web:latest
    ports:
      - "5100:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
